cron workflow

diff --git a/.github/workflows/custom-schedule.yaml b/.github/workflows/custom-schedule.yaml
--- a/.github/workflows/custom-schedule.yaml
+++ b/.github/workflows/custom-schedule.yaml
@@ -2,4 +2,21 @@ name: example schedule action
 on:
   schedule:
    - cron: 10 * * * * 
-jobs: 
+jobs:
+  test_schedule:
+    runs-on: ubuntu-latest
+    steps:
+      - name: cron mismatch
+        if: github.event.schedule != '10 * * * *'
+        run: echo "cron execution mismatch"
+
+      - name: cron match
+        if: github.event.schedule == '10 * * * *'
+        run: |
+          echo "Custom script starting"
+          echo "This is the date today $(date)"
+          if [ $? -ne 0 ]; then
+            echo "failed"
+          else
+            echo "success"
+          fi
